name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required.
  - pip
  - Deprecated >= 1.2.14
  - flake8>=5.0.4
  - librosa>=0.10.1
  - mypy>=0.982
  - numpy>=1.21.6,<2.0
  - pandas>=1.3.5
  - pytest>=7.4.3
  - requests>=2.31.0
  - tqdm>=4.66.1
  - types-decorator>=5.1.8.3

  - pip:
    - types-Deprecated
    - types-PyYAML