name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required.
  # NOW tey are copied from soundata. Review.
  - pip
  - flake8>=5.0.4
  - librosa>=0.10.0
  - mypy>=0.982
  - numpy>=1.21.6
  - pandas>=1.3.5
  - pytest>=7.2.0
  - requests>=2.31.0
  - tqdm>=4.65.0
  - types-decorator>=5.1.8.3
  - Deprecated >= 1.2.13

  - pip:
    - jams>=0.3.4
    - types-Deprecated