name: mirdata-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - chardet>=5.0.0
  - Deprecated>=1.2.14
  - h5py>=3.7.0
  - librosa>=0.10.1
  - numpy>=1.21.6,<2.0
  - openpyxl>=3.0.10
  - pandas>=1.3.5
  - pyyaml>=6.0
  - requests>=2.31.0
  - scipy>=1.7.3
  - tqdm>=4.66.1
  #######
  - libvorbis

  # optional, but required for testing
  - pytest>=7.4.3
  - pytest-pep8>=1.0.6
  - pytest-cov>=4.1.0
  - pytest-mock>=3.11.1
  - pytest-localserver>=0.8.1
  - pytest-xdist>=3.3.1

  - pip:
    - attrs>=23.1.0
    - black>=23.3.0
    - coveralls>=3.3.1
    - dali-dataset>=1.1
    - decorator>=5.1.1
    - future>=0.18.3
    - music21>=7.3.3
    - pretty_midi>=0.2.10
    - smart_open[all]>=6.4.0
    - testcontainers>=3.7.1
    - mir_eval>=0.7