name: mirdata-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - librosa>=0.10.0
  - numpy>=1.21.6
  - pandas>=1.3.5
  - requests>=2.31.0
  - tqdm>=4.65.0

  # optional, but required for testing
  - pytest>=7.2.0
  - pytest-pep8>=1.0.6
  - pytest-cov>=4.1.0
  - pytest-mock>=3.10.0
  - pytest-localserver>=0.7.1
  - pytest-xdist>=2.3.0

  - pip:
    - black>=23.3.0
    - coveralls>=3.3.1
    - future>=0.18.3
    - jams>=0.3.4
    - testcontainers>=3.7.1